# Generated by Django 5.2.8 on 2025-11-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0012_departmenttypes_price'),
        ('reception', '0010_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_result', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('n', 'NEW'), ('ip', 'IN_PROGRESS'), ('f', 'FINISHED')], default='n', max_length=100)),
                ('department_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.departmenttypes')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='analysis/')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.analysis')),
            ],
        ),
    ]
