# Generated by Django 5.2.8 on 2025-11-14 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_analysis_analysis_result_and_more'),
        ('reception', '0018_alter_patient_gender_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
    ]
