# Generated by Django 5.2.8 on 2025-11-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_departmenttypes_price'),
        ('laboratory', '0005_alter_analysis_patient'),
        ('reception', '0019_alter_patient_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='department_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_types', to='department.departmenttypes'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='reception.patient'),
        ),
    ]
