# Generated by Django 5.2.8 on 2025-11-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_alter_analysis_department_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='norma',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
