# Generated by Django 5.2.8 on 2025-11-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfile',
            name='analysis',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='AnalysisFile',
        ),
    ]
