# Generated by Django 5.2.8 on 2025-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_remove_patient_doctor_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(blank=True, choices=[('r', 'IN REGISTER'), ('l', 'IN LABORATORY'), ('d', 'IN DOCTOR'), ('t', 'TREATING'), ('f', 'FINISHED'), ('rc', 'RECOVERED')], max_length=100, null=True),
        ),
    ]
