# Generated by Django 5.2.8 on 2025-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='partial_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Agar qisman to'langan bo'lsa, summa", max_digits=10, null=True),
        ),
    ]
