# Generated by Django 5.2.8 on 2025-11-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_patient_partial_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
