# Generated by Django 5.2.8 on 2025-11-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0012_patient_paid_amount_patient_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='partial_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Agar qisman to'langan bo'lsa, summa", max_digits=10),
        ),
    ]
