# Generated by Django 5.2.8 on 2025-11-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_alter_patient_partial_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='partial_payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
