# Generated by Django 5.2.8 on 2025-11-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_departmenttypes_price'),
        ('reception', '0014_alter_patient_partial_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.departmenttypes'),
        ),
    ]
