# Generated by Django 5.2.8 on 2025-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0015_patient_department_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
