# Generated by Django 5.2.8 on 2025-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0018_alter_patient_gender_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('r', 'IN REGISTER'), ('l', 'IN LABORATORY'), ('d', 'IN DOCTOR'), ('t', 'TREATING'), ('f', 'FINISHED'), ('rc', 'RECOVERED')], default='r', max_length=100),
        ),
    ]
