# Generated by Django 5.2.8 on 2025-11-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0021_analysis_analysisresult_analysis_analysisfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis',
        ),
    ]
