# Generated by Django 5.2.8 on 2025-11-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0022_remove_analysisresult_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='reception.analysis'),
        ),
    ]
