# Generated by Django 5.2.8 on 2025-11-20 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0023_analysisresult_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
