# Generated by Django 5.2.8 on 2025-11-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0024_remove_analysisresult_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='reception.patient'),
        ),
    ]
