# Generated by Django 5.2.8 on 2025-11-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0026_patient_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease_ru',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease_uz',
        ),
    ]
