# Generated by Django 5.2.8 on 2025-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0028_remove_patient_disease_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='self_disease',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
