# Generated by Django 5.2.8 on 2026-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_alter_result_options'),
        ('reception', '0029_patient_self_disease'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['created_at'], name='reception_a_created_ad66f8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status'], name='reception_a_status_b633c4_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['created_at'], name='reception_a_created_dfb9d3_idx'),
        ),
    ]
