# Generated by Django 5.2.8 on 2026-03-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_alter_result_options'),
        ('reception', '0030_analysis_reception_a_created_ad66f8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfile',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.analysis'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='partial_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status', 'created_at'], name='reception_a_status_f33a4d_idx'),
        ),
    ]
