# Generated by Django 5.2.8 on 2026-03-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0031_alter_analysisfile_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('n', 'NEW'), ('ip', 'IN_PROGRESS'), ('f', 'FINISHED')], db_index=True, default='n', max_length=100),
        ),
    ]
