# Generated by Django 5.2.8 on 2025-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_phone_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
