# Generated by Django 5.2.8 on 2025-11-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
