# Generated by Django 5.2.8 on 2025-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
