# Generated by Django 5.2.8 on 2025-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('s', 'superadmin'), ('r', 'reception'), ('l', 'laboratory'), ('d', 'doctor'), ('c', 'cashier')], max_length=10, null=True),
        ),
    ]
