# Generated by Django 5.2.8 on 2025-11-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('reception', '0002_remove_patient_doctor_patient_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
