# Generated by Django 5.2.8 on 2025-11-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_delete_doctor'),
        ('reception', '0017_patient_created_at_patient_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(max_length=500)),
                ('recommendation', models.TextField(max_length=500)),
                ('recipe', models.TextField(max_length=500)),
                ('patient_status', models.CharField(blank=True, choices=[('r', 'IN REGISTER'), ('l', 'IN LABORATORY'), ('d', 'IN DOCTOR'), ('t', 'TREATING'), ('f', 'FINISHED'), ('rc', 'RECOVERED')], max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
            ],
        ),
    ]
