# Generated by Django 5.2.8 on 2025-11-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='diagnosis_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='diagnosis_uz',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='recipe_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='recipe_uz',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='recommendation_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='recommendation_uz',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
