# Generated by Django 5.2.8 on 2025-11-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_consultations_diagnosis_ru_and_more'),
        ('reception', '0019_alter_patient_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='reception.patient'),
        ),
    ]
