# Generated by Django 5.2.8 on 2025-11-14 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_consultations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
