# Generated by Django 5.2.8 on 2025-11-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_consultations_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultations',
            name='diagnosis_ru',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='diagnosis_uz',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='recipe_ru',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='recipe_uz',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='recommendation_ru',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='recommendation_uz',
        ),
    ]
