# Generated by Django 6.0a1 on 2025-11-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_departmenttype_department_department_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentType',
            new_name='DepartmentTypes',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_type',
            new_name='department_types',
        ),
    ]
