# Generated by Django 6.0a1 on 2025-11-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_rename_departmenttype_departmenttypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departmenttypes',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='departmenttypes',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
