# Generated by Django 6.0a1 on 2025-11-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_title_ru_department_title_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttypes',
            options={'verbose_name': 'Department Types', 'verbose_name_plural': 'Department Types'},
        ),
        migrations.AlterModelTable(
            name='departmenttypes',
            table='department_types',
        ),
    ]
