# Generated by Django 5.2.8 on 2025-11-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_departmenttypes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
