# Generated by Django 5.2.8 on 2025-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_department_options_alter_department_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_types',
        ),
        migrations.AddField(
            model_name='department',
            name='department_types',
            field=models.ManyToManyField(blank=True, null=True, to='department.departmenttypes'),
        ),
    ]
