# Generated by Django 5.2.8 on 2025-11-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_remove_department_department_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_types',
            field=models.ManyToManyField(to='department.departmenttypes'),
        ),
    ]
