# Generated by Django 5.2.8 on 2025-11-11 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_department_department_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_types',
        ),
        migrations.AddField(
            model_name='departmenttypes',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
