# Generated by Django 5.2.8 on 2025-11-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_remove_department_department_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttypes',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_types', to='department.department'),
        ),
    ]
