# Generated by Django 5.2.8 on 2025-11-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_alter_departmenttypes_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttypes',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
