# Generated by Django 5.2.8 on 2025-11-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_alter_analysisresult_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
